services:
    web:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/var/www/app
            - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./docker/supervisor/app.conf:/etc/supervisor/conf.d/app.conf
            - ./docker/php/xdebug-dev.ini:/usr/local/etc/php/conf.d-dev/xdebug-dev.ini
            - ./docker/phpmyadmin/config.inc.php:/usr/share/phpmyadmin/config.inc.php
        restart: unless-stopped
        ports:
            - ${DOCKER_PORT}:80
        extra_hosts:
            - "mitkov-systems.local:127.0.0.1"
        env_file: ./.docker.env
        depends_on:
            - mysql
        networks:
            - common
    mysql:
        image: mysql:8.0.39
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/import:/var/www/import
            #- ./docker/mysql/my.cnf:/etc/mysql/my2.cnf
        restart: unless-stopped
        env_file: ./.docker.env
        networks:
            - common
networks:
    common:
        driver: bridge
